# Generated by Django 4.1.2 on 2022-10-11 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_modifier_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.section'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='modifiers', to='api.item'),
        ),
    ]
